# Generated by Django 2.0.5 on 2018-05-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PilkaNozna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mecz',
            options={},
        ),
    ]
