# Generated by Django 2.0.5 on 2018-05-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PilkaNozna', '0002_auto_20180514_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mecz',
            options={'verbose_name_plural': 'Mecz'},
        ),
    ]
