# Generated by Django 2.0.5 on 2018-05-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PilkaNozna', '0003_auto_20180514_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statystyki_gracza',
            name='id_statystyki',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
