# Generated by Django 2.0.4 on 2018-05-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PilkaNozna', '0004_auto_20180514_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statystyki_gracza',
            name='czerwona',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=0),
        ),
        migrations.AlterField(
            model_name='statystyki_gracza',
            name='zolta',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0),
        ),
    ]
