# Generated by Django 2.0.4 on 2018-06-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PilkaNozna', '0005_auto_20180529_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statystyki_gracza',
            name='asysty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statystyki_gracza',
            name='faule',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statystyki_gracza',
            name='gole',
            field=models.IntegerField(),
        ),
    ]
